language: python
dist: trusty
python:
  - "2.7"
  - "3.4"
  - "3.6.4"

install:
  - sudo apt-get -y install iputils-ping
  - pip install --upgrade pip
  - pip install numpy pexpect
# command to run tests
script: python testunit.py
